<?php

namespace ApiExport\Module\App\Business\Feed\Parser;

/**
 * Class Common.
 */
class Common extends AbstractParser
{
    public function parse($type)
    {
        return parent::parse($type); // TODO: Change the autogenerated stub
    }

    public function parseStream($url, $type)
    {
        // TODO: Implement parseStream() method.
    }
}
