<?php

namespace ApiExport\Module\App\Business\Feed\Parser;

/**
 * Class Gfycat.
 */
class Gfycat extends AbstractParser
{
    public function parse($type)
    {
        return parent::parse($type); // TODO: Change the autogenerated stub
    }

    /**
     * @param $url
     * @param $realType
     */
    public function parseStream($url, $realType)
    {
        // TODO: Implement parseStream() method.
    }
}
