<?php

namespace ApiExport\Module\App\Business\Feed\Parser;

/**
 * Class Imgur.
 */
class Imgur extends AbstractParser
{
    public function parse($type)
    {
        return parent::parse($type); // TODO: Change the autogenerated stub
    }

    public function parseStream($url, $realType)
    {
        $return = [];
        $parsedStream = $this->streamContent($url);
        $document = new \DOMDocument();
        $document->loadHTML($parsedStream);

        $finder = new \DOMXPath($document);
        $images = $finder->query('//div[@class="wrapper"]/div/div/div/a');
        if ($images instanceof \DOMNodeList) {
            /** @var \DomElement $element */
            foreach ($images as $element) {
                $link = $element->getAttribute('href');
                if (preg_match(sprintf(self::EXT, implode('|', $this->allowedExtensions)), $link)) {
                    $return[] = $link;
                }
            }
        }

        return $return;
    }
}