config.routes.app:
  index:
      pattern:  /
      defaults: { _controller: 'IndexController::indexAction' }
      method: GET
  view:
      pattern:  /view
      defaults: { _controller: 'IndexController::viewAction' }
      method: GET
  feedItem:
      pattern:  /feed-item
      defaults: { _controller: 'FeedItemController::getAction' }
      method: GET
  feedItemStat:
      pattern:  /feed-item-stats
      defaults: { _controller: 'FeedItemController::getStatisticsItemAction' }
      method: GET
  feedStat:
      pattern:  /feed-stats
      defaults: { _controller: 'FeedItemController::getStatisticsFeedAction' }
      method: GET
  createFeedItems:
      pattern:  /create-items
      defaults: { _controller: 'FeedItemController::createAction' }
      method: GET
  updateFeedItem:
      pattern:  /update-item
      defaults: { _controller: 'FeedItemController::updateAction' }
      method: POST
