config.routes.app:
  index:
      pattern:  /
      defaults: { _controller: 'IndexController::indexAction' }
      method: GET
  feedItem:
      pattern:  /feed-item
      defaults: { _controller: 'FeedItemController::getAction' }
      method: GET
  createFeedItems:
      pattern:  /create-items
      defaults: { _controller: 'FeedItemController::createAction' }
      method: GET
  updateFeedItem:
      pattern:  /update-item
      defaults: { _controller: 'FeedItemController::updateAction' }
      method: POST

